using System;
using System.Collections.Generic; //for ICollection

namespace FEH_Planner.Models
{
    public class MoveType
    {
        //primary key (generated by DB)
        public int MoveTypeID { get; set; }
        public string Name { get; set; }

        //foreign key in Unit
        public virtual ICollection<Unit> UnitMoveTypes { get; set; }
    }
}
