using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic; //for ICollection

namespace FEH_Planner.Models
{
    public class Skill
    {
        //primary key (generated by DB)
        public int SkillID { get; set; }

        public string Name { get; set; }
        public char Slot { get; set; }
        public int SP { get; set; }
        public string Description { get; set; }
        public bool Inheritable{ get; set; }

        //for foreign keys in Build
        public virtual ICollection<Build> BuildWeapons { get; set; }
        public virtual ICollection<Build> BuildA_Skills { get; set; }
        public virtual ICollection<Build> BuildB_Skills { get; set; }
        public virtual ICollection<Build> BuildC_Skills { get; set; }
        public virtual ICollection<Build> BuildS_Skills { get; set; }
    }
}
