using System;
using System.Collections.Generic; //for ICollection

namespace FEH_Planner.Models
{
    public class Slot
    {
        //primary key (generated by DB)
        public int SlotID { get; set; }
        public string Name { get; set; }

        //for foreign keys in Skill
        public virtual ICollection<Skill> SkillSlots { get; set; }
    }
}
